# Generated by Django 5.2.7 on 2025-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration_min', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('premiere', models.DateTimeField()),
                ('age_rating', models.IntegerField()),
            ],
        ),
    ]
